=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/events.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (event)*>
<!ELEMENT event (parameter|on_start|on_stop|on_init|on_time|objects)*>
<!ATTLIST event
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT on_start  (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on_stop   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on_init   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT if        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT ifnot     (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT else      (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ATTLIST if
	name CDATA #REQUIRED>
<!ATTLIST ifnot
	name CDATA #REQUIRED>
<!ELEMENT on_time (on)*>
<!ATTLIST on
	time CDATA #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ATTLIST start
	name CDATA #REQUIRED>
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop
	name CDATA #REQUIRED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	name CDATA #REQUIRED>
<!ELEMENT open (#PCDATA)>
<!ATTLIST open
	name CDATA #REQUIRED>
<!ELEMENT close (#PCDATA)>
<!ATTLIST close
	name CDATA #REQUIRED>
<!ELEMENT active (#PCDATA)>
<!ATTLIST active
	name CDATA #REQUIRED>
<!ELEMENT deactive (#PCDATA)>
<!ATTLIST deactive
	name CDATA #REQUIRED>
<!ELEMENT refresh (#PCDATA)>
<!ATTLIST refresh
	name CDATA #REQUIRED>
<!ELEMENT init (#PCDATA)>
<!ATTLIST init
	name CDATA #REQUIRED>
<!ELEMENT announce (#PCDATA)>
<!ATTLIST announce
	msg_id CDATA #IMPLIED
	val CDATA #IMPLIED>
<!ELEMENT despawn (#PCDATA)>
<!ATTLIST despawn
	name CDATA #REQUIRED>
<!ELEMENT respawn (#PCDATA)>
<!ATTLIST respawn
	name CDATA #REQUIRED>
<!ELEMENT global_add_reward (#PCDATA)>
<!ATTLIST global_add_reward
	name CDATA #REQUIRED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>
<!ELEMENT global_remove_reward (#PCDATA)>
<!ATTLIST global_remove_reward
	name CDATA #REQUIRED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>
<!ELEMENT global_remove_items (#PCDATA)>
<!ATTLIST global_remove_items
	name CDATA #REQUIRED>
<!ELEMENT objects (door|spawn|spawn_ex|spawn_npc|point|boat_point|static_object|siege_toggle_npc|castle_zone|combat_flag|ctb_team|cmg_arena|territory_ward|zone|reward|rewardlist|abnormal|item)*>
<!ATTLIST objects
	name CDATA #REQUIRED>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ELEMENT siege_toggle_npc (objects)*>
<!ATTLIST siege_toggle_npc
	id CDATA #REQUIRED
	fake_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	hp CDATA #REQUIRED>
<!ELEMENT castle_zone (#PCDATA)>
<!ATTLIST castle_zone
	name CDATA #REQUIRED
	price CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED>
<!ELEMENT static_object (#PCDATA)>
<!ATTLIST static_object
	id CDATA #REQUIRED>
<!ELEMENT spawn_ex (#PCDATA)>
<!ATTLIST spawn_ex
	name CDATA #REQUIRED>
<!ELEMENT spawn_npc (#PCDATA)>
<!ATTLIST spawn_npc
	id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT combat_flag (#PCDATA)>
<!ATTLIST combat_flag
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT territory_ward (#PCDATA)>
<!ATTLIST territory_ward
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT ctb_team (#PCDATA)>
<!ATTLIST ctb_team
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #REQUIRED
	id CDATA #REQUIRED
	mob_id CDATA #REQUIRED>
<!ELEMENT cmg_arena (#PCDATA)>
<!ELEMENT boat_point (#PCDATA)>
<!ATTLIST boat_point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	speed1 CDATA #REQUIRED
	speed2 CDATA #REQUIRED
	fuel CDATA #IMPLIED
	teleport CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT npc_say (add)*>
<!ATTLIST npc_say
	npc CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT add (#PCDATA)*>
<!ATTLIST add
	value CDATA #REQUIRED>
<!ELEMENT teleport_players (#PCDATA)*>
<!ATTLIST teleport_players
	id CDATA #REQUIRED>
<!ELEMENT say (#PCDATA)>
<!ATTLIST say
	how CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT play_sound (#PCDATA)>
<!ATTLIST play_sound
	type CDATA #REQUIRED
	sound CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT give_item (#PCDATA)>
<!ATTLIST give_item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT rewardlist (group|reward)*>
<!ATTLIST rewardlist
	type CDATA #REQUIRED>
<!ELEMENT group (reward)*>
<!ATTLIST group
	chance CDATA #IMPLIED>
<!ELEMENT reward (#PCDATA)>
<!ATTLIST reward
	chance CDATA #REQUIRED
	item_id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED>
<!ELEMENT abnormal (#PCDATA)>
<!ATTLIST abnormal
		name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED
	count CDATA #IMPLIED>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/siege/[115] dragonspine_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="115" name="Dragonspine Fortress" impl="FortressSiege">
		<on_init>
			<spawn name="fortress_peace_npcs"/>
			<init name="upgradeable_doors"/>
			<init name="commander_doors"/>
			<init name="enter_doors"/>
			<init name="siege_zones"/>
			<init name="flag_zones"/>
			<spawn name="flag_pole"/>
			<spawn name="peace_commanders"/>
		</on_init>
		<on_start>
			<despawn name="peace_commanders"/>
			<!--Спавним гвардов-->
			<spawn name="default_guards"/>
			<spawn name="guards_live_with_c_center"/>
			<spawn name="siege_commanders"/>
			<if name="old_owner">
				<spawn name="owner_flagdef"/>
				<spawn name="mercenary"/>
			</if>
			<else>
				<spawn name="noowner_flagdef"/>
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1"/>
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2"/>
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens"/>
			</if>
			<!--Обновляем двери-->
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<active name="siege_zones"/>
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="owner_flagdef"/>
				<despawn name="mercenary"/>
			</if>
			<else>
				<despawn name="noowner_flagdef"/>
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards"/>
			<despawn name="guards_live_with_c_center"/>
			<despawn name="siege_commanders"/>

			<!--Капитаны и менчант-->
			<spawn name="peace_commanders"/>

			<!--Обновляем двери-->
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<teleport_players id="spectators"/>
			<deactive name="siege_zones"/>
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600"/>
			</on>
			<on time="-1800">
				<announce val="1800"/>
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600"/>
				<stop name="registration"/>
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5"/>
			</on>
			<on time="-4">
				<announce val="4"/>
			</on>
			<on time="-3">
				<announce val="3"/>
			</on>
			<on time="-2">
				<announce val="2"/>
			</on>
			<on time="-1">
				<announce val="1"/>
			</on>
			<on time="0">
				<start name="event"/>
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="600">
				<give_item id="-300" count="310"/>
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="900">
				<give_item id="-300" count="310"/>
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="1200">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="1500">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="1800">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="2100">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="2400">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="2700">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="3000">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="3300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="3600">
				<stop name="event"/>
			</on>
		</on_time>
		<objects name="fortress_peace_npcs">
			<spawn name="dragonspine_fortress_115"/>
		</objects>
		<objects name="merchant">
			<spawn_ex name="dragonspine_fortress_peace_merchant"/>
		</objects>
		<objects name="flag_pole">
			<static_object id="20200500"/>
		</objects>
		<objects name="combat_flags">
			<combat_flag x="11459" y="95308" z="-3264"/>
			<combat_flag x="11527" y="95301" z="-3264"/>
			<combat_flag x="11623" y="95311" z="-3264"/>
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="dragonspine_fortress_peace_commanders"/>
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="dragonspine_fortress_siege_commanders"/>
		</objects>
		<objects name="envoy">
			<spawn_ex name="dragonspine_fortress_envoy"/>
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="dragonspine_fortress_default_guards"/>
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="dragonspine_fortress_live_with_c_center"/>
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="dragonspine_fortress_noowner_flagdef"/>
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="dragonspine_fortress_owner_flagdef"/>
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="dragonspine_fortress_gunner"/>
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="dragonspine_fortress_reinforce_1"/>
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="dragonspine_fortress_reinforce_2"/>
		</objects>
		<objects name="enter_doors">
			<door id="20200001"/>
			<door id="20200008"/>
		</objects>
		<objects name="upgradeable_doors">
			<door id="20200001"/>
			<door id="20200008"/>
			<door id="20200004"/>
			<door id="20200005"/>
		</objects>
		<objects name="commander_doors">
			<door id="20200002"/>
			<door id="20200003"/>
			<door id="20200006"/>
			<door id="20200007"/>
		</objects>
		<objects name="mercenary_points">
			<point x="12411" y="92659" z="-3448"/>
			<point x="12369" y="92881" z="-3432"/>
			<point x="12421" y="93075" z="-3424"/>
			<point x="12486" y="93221" z="-3424"/>
			<point x="12487" y="93408" z="-3424"/>
			<point x="12495" y="93748" z="-3424"/>
			<point x="12436" y="93978" z="-3424"/>
			<point x="12173" y="94091" z="-3424"/>
			<point x="11895" y="94112" z="-3424"/>
			<point x="11545" y="94266" z="-3424"/>
		</objects>
		<objects name="mercenary">
			<spawn_ex name="dragonspine_fortress_mercenary"/>
		</objects>
		<objects name="siege_zones">
			<zone name="[di_ore_fort_siege]"/>
		</objects>
		<objects name="flag_zones">
			<zone name="[di_ore_fort_hq]"/>
		</objects>
	</event>
</list>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/custom/events/pvp/[5] hasher_hard.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="5" name="Hasher Hard" impl="PvP">
		<parameter name="enabled" value="false"/>
		<parameter name="start_time" value="45 * * * *"/>	<!--Время проведения ивента в формате cron.-->
		<parameter name="min_level" value="85"/>
		<parameter name="max_level" value="105"/>
		<parameter name="min_players" value="10"/>
		<parameter name="teams" value="1"/>
		<parameter name="count_die_from_exit" value="3"/>
		<parameter name="min_kill_from_reward" value="1"/>
		<parameter name="min_kill_team_from_reward" value="1"/>
		<parameter name="hide_nick" value="true"/>
		<parameter name="buffs" value="11517,1;11518,1;11519,1;11520,1;11521,1;11522,1;11529,1;11530,1;11532,1;11565,1;11566,1;11567,1"/>
		<parameter name="add_hero_last_player" value="false"/>

		<on_time>
			<on time="0">
				<start name="registration"/>
			</on>
			<on time="300">
				<stop name="registration"/>
			</on>
			<on time="330">
				<start name="sort"/>
				<start name="teleport"/>
			</on>
			<on time="360">
				<start name="battle"/>
			</on>
			<on time="660">
				<stop name="battle"/>
			</on>
		</on_time>

		<objects name="team0">
			<point x="20440" y="254488" z="-2046"/>
			<point x="19816" y="254488" z="-2045"/>
			<point x="19064" y="254488" z="-2043"/>
			<point x="18552" y="254392" z="-2044"/>
			<point x="18056" y="253880" z="-2044"/>
			<point x="17944" y="253240" z="-2044"/>
			<point x="17992" y="252648" z="-2046"/>
			<point x="18456" y="252440" z="-2046"/>
			<point x="18888" y="252392" z="-2043"/>
			<point x="19288" y="252376" z="-2042"/>
			<point x="19800" y="252392" z="-2043"/>
			<point x="20296" y="252488" z="-2043"/>
			<point x="20696" y="252776" z="-2043"/>
			<point x="20904" y="253240" z="-2042"/>
			<point x="20936" y="253720" z="-2044"/>
			<point x="21448" y="252888" z="-2044"/>
			<point x="22152" y="252744" z="-2045"/>
			<point x="21896" y="252088" z="-2042"/>
			<point x="17864" y="252216" z="-2045"/>
			<point x="17448" y="251688" z="-2039"/>
			<point x="17432" y="251144" z="-2002"/>
			<point x="18040" y="250856" z="-1999"/>
			<point x="18744" y="250648" z="-2031"/>
			<point x="19352" y="250600" z="-2044"/>
			<point x="19992" y="250568" z="-2038"/>
		</objects>

		<objects name="abnormal0">
			<abnormal name="CHANGE_VES_D"/>
		</objects>

		<objects name="reward_for_kill">
			<reward item_id="4357" min="1" max="1" chance="100.0"/>
		</objects>
		<objects name="reward_for_win_team">
			<reward item_id="4037" min="1" max="1" chance="100.0"/>
		</objects>
	</event>
</list>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/siege/[120] demon_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="120" name="Demon Fortress" impl="FortressSiege">
		<on_init>
			<spawn name="fortress_peace_npcs"/>
			<init name="upgradeable_doors"/>
			<init name="commander_doors"/>
			<init name="enter_doors"/>
			<init name="siege_zones"/>
			<init name="flag_zones"/>
			<spawn name="flag_pole"/>
			<spawn name="peace_commanders"/>
		</on_init>
		<on_start>
			<despawn name="peace_commanders"/>
			<!--Спавним гвардов-->
			<spawn name="default_guards"/>
			<spawn name="guards_live_with_c_center"/>
			<spawn name="siege_commanders"/>
			<if name="old_owner">
				<spawn name="owner_flagdef"/>
				<spawn name="mercenary"/>
			</if>
			<else>
				<spawn name="noowner_flagdef"/>
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1"/>
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2"/>
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens"/>
			</if>
			<!--Обновляем двери-->
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<active name="siege_zones"/>
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="owner_flagdef"/>
				<despawn name="mercenary"/>
			</if>
			<else>
				<despawn name="noowner_flagdef"/>
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards"/>
			<despawn name="guards_live_with_c_center"/>
			<despawn name="siege_commanders"/>

			<!--Капитаны и менчант-->
			<spawn name="peace_commanders"/>

			<!--Обновляем двери-->
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<teleport_players id="spectators"/>
			<deactive name="siege_zones"/>
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600"/>
			</on>
			<on time="-1800">
				<announce val="1800"/>
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600"/>
				<stop name="registration"/>
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5"/>
			</on>
			<on time="-4">
				<announce val="4"/>
			</on>
			<on time="-3">
				<announce val="3"/>
			</on>
			<on time="-2">
				<announce val="2"/>
			</on>
			<on time="-1">
				<announce val="1"/>
			</on>
			<on time="0">
				<start name="event"/>
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="600">
				<give_item id="-300" count="310"/>
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="900">
				<give_item id="-300" count="310"/>
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="1200">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="1500">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="1800">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="2100">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="2400">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="2700">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="3000">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="3300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="3600">
				<stop name="event"/>
			</on>
		</on_time>
		<objects name="fortress_peace_npcs">
			<spawn name="demon_fortress_120"/>
		</objects>
		<objects name="merchant">
			<spawn_ex name="demon_fortress_peace_merchant"/>
		</objects>
		<objects name="flag_pole">
			<static_object id="23160500"/>
		</objects>
		<objects name="combat_flags">
			<combat_flag x="100462" y="-55413" z="-488"/>
			<combat_flag x="100455" y="-55343" z="-488"/>
			<combat_flag x="100455" y="-55253" z="-488"/>
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="demon_fortress_peace_commanders"/>
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="demon_fortress_siege_commanders"/>
		</objects>
		<objects name="envoy">
			<spawn_ex name="demon_fortress_envoy"/>
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="demon_fortress_default_guards"/>
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="demon_fortress_live_with_c_center"/>
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="demon_fortress_noowner_flagdef"/>
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="demon_fortress_owner_flagdef"/>
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="demon_fortress_gunner"/>
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="demon_fortress_reinforce_1"/>
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="demon_fortress_reinforce_2"/>
		</objects>
		<objects name="enter_doors">
			<door id="23160001"/>
			<door id="23160008"/>
		</objects>
		<objects name="upgradeable_doors">
			<door id="23160001"/>
			<door id="23160008"/>
			<door id="23160003"/>
			<door id="23160002"/>
		</objects>
		<objects name="commander_doors">
			<door id="23160004"/>
			<door id="23160005"/>
			<door id="23160007"/>
			<door id="23160006"/>
		</objects>
		<objects name="mercenary_points">
			<point x="103619" y="-56700" z="-768"/>
			<point x="103133" y="-56351" z="-744"/>
			<point x="102743" y="-55914" z="-680"/>
			<point x="102600" y="-55422" z="-648"/>
			<point x="102492" y="-54417" z="-632"/>
			<point x="102260" y="-54359" z="-640"/>
			<point x="101957" y="-54356" z="-640"/>
			<point x="101693" y="-54515" z="-640"/>
			<point x="101628" y="-54814" z="-640"/>
			<point x="101441" y="-55310" z="-640"/>
		</objects>
		<objects name="mercenary">
			<spawn_ex name="demon_fortress_mercenary"/>
		</objects>
		<objects name="siege_zones">
			<zone name="[ru_go_fort_siege]"/>
		</objects>
		<objects name="flag_zones">
			<zone name="[ru_go_fort_hq]"/>
		</objects>
	</event>
</list>
