=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/events.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (event)*>
<!ELEMENT event (parameter|on_start|on_stop|on_init|on_time|objects)*>
<!ATTLIST event
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT on_start  (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on_stop   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on_init   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT if        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT ifnot     (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT else      (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ATTLIST if
	name CDATA #REQUIRED>
<!ATTLIST ifnot
	name CDATA #REQUIRED>
<!ELEMENT on_time (on)*>
<!ATTLIST on
	time CDATA #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ATTLIST start
	name CDATA #REQUIRED>
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop
	name CDATA #REQUIRED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	name CDATA #REQUIRED>
<!ELEMENT open (#PCDATA)>
<!ATTLIST open
	name CDATA #REQUIRED>
<!ELEMENT close (#PCDATA)>
<!ATTLIST close
	name CDATA #REQUIRED>
<!ELEMENT active (#PCDATA)>
<!ATTLIST active
	name CDATA #REQUIRED>
<!ELEMENT deactive (#PCDATA)>
<!ATTLIST deactive
	name CDATA #REQUIRED>
<!ELEMENT refresh (#PCDATA)>
<!ATTLIST refresh
	name CDATA #REQUIRED>
<!ELEMENT init (#PCDATA)>
<!ATTLIST init
	name CDATA #REQUIRED>
<!ELEMENT announce (#PCDATA)>
<!ATTLIST announce
	msg_id CDATA #IMPLIED
	val CDATA #IMPLIED>
<!ELEMENT despawn (#PCDATA)>
<!ATTLIST despawn
	name CDATA #REQUIRED>
<!ELEMENT respawn (#PCDATA)>
<!ATTLIST respawn
	name CDATA #REQUIRED>
<!ELEMENT global_add_reward (#PCDATA)>
<!ATTLIST global_add_reward
	name CDATA #REQUIRED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>
<!ELEMENT global_remove_reward (#PCDATA)>
<!ATTLIST global_remove_reward
	name CDATA #REQUIRED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>
<!ELEMENT global_remove_items (#PCDATA)>
<!ATTLIST global_remove_items
	name CDATA #REQUIRED>
<!ELEMENT objects (door|spawn|spawn_ex|spawn_npc|point|boat_point|static_object|siege_toggle_npc|castle_zone|combat_flag|ctb_team|cmg_arena|territory_ward|zone|reward|rewardlist|abnormal|item)*>
<!ATTLIST objects
	name CDATA #REQUIRED>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ELEMENT siege_toggle_npc (objects)*>
<!ATTLIST siege_toggle_npc
	id CDATA #REQUIRED
	fake_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	hp CDATA #REQUIRED>
<!ELEMENT castle_zone (#PCDATA)>
<!ATTLIST castle_zone
	name CDATA #REQUIRED
	price CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED>
<!ELEMENT static_object (#PCDATA)>
<!ATTLIST static_object
	id CDATA #REQUIRED>
<!ELEMENT spawn_ex (#PCDATA)>
<!ATTLIST spawn_ex
	name CDATA #REQUIRED>
<!ELEMENT spawn_npc (#PCDATA)>
<!ATTLIST spawn_npc
	id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT combat_flag (#PCDATA)>
<!ATTLIST combat_flag
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT territory_ward (#PCDATA)>
<!ATTLIST territory_ward
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT ctb_team (#PCDATA)>
<!ATTLIST ctb_team
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #REQUIRED
	id CDATA #REQUIRED
	mob_id CDATA #REQUIRED>
<!ELEMENT cmg_arena (#PCDATA)>
<!ELEMENT boat_point (#PCDATA)>
<!ATTLIST boat_point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	speed1 CDATA #REQUIRED
	speed2 CDATA #REQUIRED
	fuel CDATA #IMPLIED
	teleport CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT npc_say (add)*>
<!ATTLIST npc_say
	npc CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT add (#PCDATA)*>
<!ATTLIST add
	value CDATA #REQUIRED>
<!ELEMENT teleport_players (#PCDATA)*>
<!ATTLIST teleport_players
	id CDATA #REQUIRED>
<!ELEMENT say (#PCDATA)>
<!ATTLIST say
	how CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT play_sound (#PCDATA)>
<!ATTLIST play_sound
	type CDATA #REQUIRED
	sound CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT give_item (#PCDATA)>
<!ATTLIST give_item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT rewardlist (group|reward)*>
<!ATTLIST rewardlist
	type CDATA #REQUIRED>
<!ELEMENT group (reward)*>
<!ATTLIST group
	chance CDATA #IMPLIED>
<!ELEMENT reward (#PCDATA)>
<!ATTLIST reward
	chance CDATA #REQUIRED
	item_id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED>
<!ELEMENT abnormal (#PCDATA)>
<!ATTLIST abnormal
		name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED
	count CDATA #IMPLIED>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/pvp/[4] krateis_cube_80-85.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="4" name="Krateis Cube 80-85 Level" impl="KrateisCube">
		<parameter name="min_level" value="80"/>
		<parameter name="max_level" value="85"/>
		<on_init>
			<init name="doors"/>
		</on_init>
		<on_start>
			<close name="doors"/>
			<spawn name="spawnlist"/>
		</on_start>
		<on_stop>
			<close name="doors"/>
			<despawn name="spawnlist"/>
		</on_stop>
		<on_time>
			<on time="-180">
				<start name="prepare"/>
			</on>
			<on time="-30">
				<announce/>
			</on>
			<on time="-29">
				<announce/>
			</on>
			<on time="-28">
				<announce/>
			</on>
			<on time="-27">
				<announce/>
			</on>
			<on time="-26">
				<announce/>
			</on>
			<on time="-25">
				<announce/>
			</on>
			<on time="-24">
				<announce/>
			</on>
			<on time="-23">
				<announce/>
			</on>
			<on time="-22">
				<announce/>
			</on>
			<on time="-21">
				<announce/>
			</on>
			<on time="-20">
				<announce/>
			</on>
			<on time="-19">
				<announce/>
			</on>
			<on time="-18">
				<announce/>
			</on>
			<on time="-17">
				<announce/>
			</on>
			<on time="-16">
				<announce/>
			</on>
			<on time="-15">
				<announce/>
			</on>
			<on time="-14">
				<announce/>
			</on>
			<on time="-13">
				<announce/>
			</on>
			<on time="-12">
				<announce/>
			</on>
			<on time="-11">
				<announce/>
			</on>
			<on time="-10">
				<announce/>
			</on>
			<on time="-9">
				<announce/>
			</on>
			<on time="-8">
				<announce/>
			</on>
			<on time="-7">
				<announce/>
			</on>
			<on time="-6">
				<announce/>
			</on>
			<on time="-5">
				<announce/>
			</on>
			<on time="-4">
				<announce/>
			</on>
			<on time="-3">
				<announce/>
			</on>
			<on time="-2">
				<announce/>
			</on>
			<on time="-1">
				<announce/>
			</on>
			<on time="0">
				<start name="event"/>
			</on>
			<on time="1195">
				<announce val="5"/>
			</on>
			<on time="1196">
				<announce val="4"/>
			</on>
			<on time="1197">
				<announce val="3"/>
			</on>
			<on time="1198">
				<announce val="2"/>
			</on>
			<on time="1199">
				<announce val="1"/>
			</on>
			<on time="1200">
				<stop name="event"/>
			</on>
		</on_time>
		<objects name="wait_locs">
			<point x="-54000" y="-83280" z="-8336"/>
			<point x="-53808" y="-83200" z="-8336"/>
			<point x="-54080" y="-82800" z="-8336"/>
			<point x="-53824" y="-82752" z="-8336"/>
			<point x="-53648" y="-83024" z="-8336"/>
		</objects>
		<objects name="teleport_locs">
			<point x="-52748" y="-86920" z="-8292"/>
			<point x="-50732" y="-86936" z="-8292"/>
			<point x="-48748" y="-86936" z="-8292"/>
			<point x="-46748" y="-86936" z="-8292"/>
			<point x="-44748" y="-86920" z="-8292"/>
			<point x="-52748" y="-84936" z="-8292"/>
			<point x="-50732" y="-84936" z="-8292"/>
			<point x="-48748" y="-84936" z="-8292"/>
			<point x="-46748" y="-84936" z="-8292"/>
			<point x="-44748" y="-84936" z="-8292"/>
			<point x="-52748" y="-82936" z="-8292"/>
			<point x="-50748" y="-82936" z="-8292"/>
			<point x="-48732" y="-82936" z="-8292"/>
			<point x="-46748" y="-82936" z="-8292"/>
			<point x="-44748" y="-82936" z="-8292"/>
			<point x="-52748" y="-80936" z="-8292"/>
			<point x="-50748" y="-80936" z="-8292"/>
			<point x="-48732" y="-80952" z="-8292"/>
			<point x="-46748" y="-80936" z="-8292"/>
			<point x="-44748" y="-80936" z="-8292"/>
			<point x="-52732" y="-78936" z="-8292"/>
			<point x="-50748" y="-78936" z="-8292"/>
			<point x="-48764" y="-78936" z="-8292"/>
			<point x="-46748" y="-78936" z="-8292"/>
			<point x="-44748" y="-78936" z="-8292"/>
		</objects>
		<objects name="doors">
			<door id="18150207"/>
			<door id="18150208"/>
			<door id="18150209"/>
			<door id="18150210"/>
			<door id="18150211"/>
			<door id="18150212"/>
			<door id="18150213"/>
			<door id="18150214"/>
			<door id="18150227"/>
			<door id="18150228"/>
			<door id="18150229"/>
			<door id="18150230"/>
			<door id="18150231"/>
			<door id="18150232"/>
			<door id="18150233"/>
			<door id="18150234"/>
			<door id="18150247"/>
			<door id="18150248"/>
			<door id="18150249"/>
			<door id="18150250"/>
			<door id="18150251"/>
			<door id="18150252"/>
			<door id="18150253"/>
			<door id="18150254"/>
			<door id="18150267"/>
			<door id="18150268"/>
			<door id="18150269"/>
			<door id="18150270"/>
			<door id="18150271"/>
			<door id="18150272"/>
			<door id="18150273"/>
			<door id="18150274"/>
			<door id="18150287"/>
			<door id="18150288"/>
			<door id="18150289"/>
			<door id="18150290"/>
			<door id="18150291"/>
			<door id="18150292"/>
			<door id="18150293"/>
			<door id="18150294"/>
			<door id="18150216"/>
			<door id="18150221"/>
			<door id="18150236"/>
			<door id="18150241"/>
			<door id="18150256"/>
			<door id="18150261"/>
			<door id="18150276"/>
			<door id="18150281"/>
			<door id="18150217"/>
			<door id="18150222"/>
			<door id="18150237"/>
			<door id="18150242"/>
			<door id="18150257"/>
			<door id="18150262"/>
			<door id="18150277"/>
			<door id="18150282"/>
			<door id="18150218"/>
			<door id="18150223"/>
			<door id="18150238"/>
			<door id="18150243"/>
			<door id="18150258"/>
			<door id="18150263"/>
			<door id="18150278"/>
			<door id="18150283"/>
			<door id="18150219"/>
			<door id="18150224"/>
			<door id="18150239"/>
			<door id="18150244"/>
			<door id="18150259"/>
			<door id="18150264"/>
			<door id="18150279"/>
			<door id="18150284"/>
			<door id="18150220"/>
			<door id="18150225"/>
			<door id="18150240"/>
			<door id="18150245"/>
			<door id="18150260"/>
			<door id="18150265"/>
			<door id="18150280"/>
			<door id="18150285"/>
		</objects>
		<objects name="spawnlist">
			<spawn_ex name="krateis_cube_80_85_room_0"/>
			<spawn_ex name="krateis_cube_80_85_room_1"/>
			<spawn_ex name="krateis_cube_80_85_room_2"/>
			<spawn_ex name="krateis_cube_80_85_room_3"/>
			<spawn_ex name="krateis_cube_80_85_room_4"/>
			<spawn_ex name="krateis_cube_80_85_room_5"/>
			<spawn_ex name="krateis_cube_80_85_room_6"/>
			<spawn_ex name="krateis_cube_80_85_room_7"/>
			<spawn_ex name="krateis_cube_80_85_room_8"/>
			<spawn_ex name="krateis_cube_80_85_room_9"/>
			<spawn_ex name="krateis_cube_80_85_room_10"/>
			<spawn_ex name="krateis_cube_80_85_room_11"/>
			<spawn_ex name="krateis_cube_80_85_room_12"/>
			<spawn_ex name="krateis_cube_80_85_room_13"/>
			<spawn_ex name="krateis_cube_80_85_room_14"/>
			<spawn_ex name="krateis_cube_80_85_room_15"/>
			<spawn_ex name="krateis_cube_80_85_room_16"/>
			<spawn_ex name="krateis_cube_80_85_room_17"/>
			<spawn_ex name="krateis_cube_80_85_room_18"/>
			<spawn_ex name="krateis_cube_80_85_room_19"/>
			<spawn_ex name="krateis_cube_80_85_room_20"/>
			<spawn_ex name="krateis_cube_80_85_room_21"/>
			<spawn_ex name="krateis_cube_80_85_room_22"/>
			<spawn_ex name="krateis_cube_80_85_room_23"/>
			<spawn_ex name="krateis_cube_80_85_room_24"/>
		</objects>
	</event>
</list>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/pvp/[1] party_vs_party_duel.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="1" name="Party Duel" impl="PartyVsPartyDuel">
		<on_time>
			<on time="-30">
				<teleport_players id="to_arena"/>
			</on>
			<on time="-3">
				<announce val="3"/>
			</on>
			<on time="-2">
				<announce val="2"/>
			</on>
			<on time="-1">
				<announce val="1"/>
			</on>
			<on time="0">
				<start name="event"/>
			</on>
			<on time="360">
				<stop name="event"/>
			</on>
		</on_time>
	</event>
</list>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/siege/[117] western_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="117" name="Western Fortress" impl="FortressSiege">
		<on_init>
			<spawn name="fortress_peace_npcs"/>
			<init name="upgradeable_doors"/>
			<init name="commander_doors"/>
			<init name="enter_doors"/>
			<init name="machine_doors"/>
			<init name="siege_zones"/>
			<init name="flag_zones"/>
			<spawn name="flag_pole"/>
			<spawn name="peace_commanders"/>
		</on_init>
		<on_start>
			<despawn name="peace_commanders"/>
			<!--Спавним гвардов-->
			<spawn name="default_guards"/>
			<spawn name="guards_live_with_c_center"/>
			<spawn name="siege_commanders"/>
			<spawn name="out_power_units"/>
			<spawn name="in_power_units"/>
			<if name="old_owner">
				<spawn name="owner_flagdef"/>
				<spawn name="mercenary"/>
			</if>
			<else>
				<spawn name="noowner_flagdef"/>
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1"/>
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2"/>
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens"/>
			</if>
			<!--Обновляем двери-->
			<refresh name="enter_doors"/>
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<refresh name="machine_doors"/>
			<active name="siege_zones"/>
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="owner_flagdef"/>
				<despawn name="mercenary"/>
			</if>
			<else>
				<despawn name="noowner_flagdef"/>
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards"/>
			<despawn name="guards_live_with_c_center"/>
			<despawn name="siege_commanders"/>
			<despawn name="out_power_units"/>
			<despawn name="in_power_units"/>

			<!--Капитаны и менчант-->
			<spawn name="peace_commanders"/>

			<!--Обновляем двери-->
			<refresh name="enter_doors"/>
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<refresh name="machine_doors"/>
			<teleport_players id="spectators"/>
			<deactive name="siege_zones"/>
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600"/>
			</on>
			<on time="-1800">
				<announce val="1800"/>
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600"/>
				<stop name="registration"/>
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5"/>
			</on>
			<on time="-4">
				<announce val="4"/>
			</on>
			<on time="-3">
				<announce val="3"/>
			</on>
			<on time="-2">
				<announce val="2"/>
			</on>
			<on time="-1">
				<announce val="1"/>
			</on>
			<on time="0">
				<start name="event"/>
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="600">
				<give_item id="-300" count="310"/>
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="900">
				<give_item id="-300" count="310"/>
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="1200">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="1500">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="1800">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="2100">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="2400">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="2700">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="3000">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="3300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="3600">
				<stop name="event"/>
			</on>
		</on_time>
		<objects name="fortress_peace_npcs">
			<spawn name="western_fortress_117"/>
		</objects>
		<objects name="merchant">
			<spawn_ex name="western_fortress_peace_merchant"/>
		</objects>
		<objects name="flag_pole">
			<static_object id="23170500"/>
		</objects>
		<objects name="combat_flags">
			<combat_flag x="111282" y="-14876" z="-864"/>
			<combat_flag x="111362" y="-14863" z="-864"/>
			<combat_flag x="111443" y="-14861" z="-864"/>
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="western_fortress_peace_commanders"/>
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="western_fortress_siege_commanders"/>
		</objects>
		<objects name="envoy">
			<spawn_ex name="western_fortress_envoy"/>
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="western_fortress_default_guards"/>
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="western_fortress_live_with_c_center"/>
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="western_fortress_noowner_flagdef"/>
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="western_fortress_owner_flagdef"/>
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="western_fortress_gunner"/>
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="western_fortress_reinforce_1"/>
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="western_fortress_reinforce_2"/>
		</objects>
		<objects name="enter_doors">
			<door id="23170001"/>
			<door id="23170012"/>
		</objects>
		<objects name="machine_doors">
			<door id="23170006"/>
			<door id="23170007"/>
		</objects>
		<objects name="upgradeable_doors">
			<door id="23170001"/>
			<door id="23170012"/>
			<door id="23170003"/>
			<door id="23170002"/>
			<door id="23170010"/>
			<door id="23170011"/>
		</objects>
		<objects name="commander_doors">
			<door id="23170008"/>
			<door id="23170009"/>
			<door id="23170005"/>
			<door id="23170004"/>
		</objects>
		<objects name="mercenary_points">
			<point x="110634" y="-11306" z="-1752"/>
			<point x="110120" y="-11093" z="-1656"/>
			<point x="109817" y="-11360" z="-1488"/>
			<point x="109668" y="-11697" z="-1400"/>
			<point x="108377" y="-13026" z="-1000"/>
			<point x="108528" y="-13286" z="-992"/>
			<point x="110366" y="-13307" z="-992"/>
			<point x="110337" y="-14038" z="-992"/>
			<point x="110964" y="-14235" z="-992"/>
			<point x="111346" y="-14444" z="-992"/>
		</objects>
		<objects name="mercenary">
			<spawn_ex name="western_fortress_mercenary"/>
		</objects>
		<objects name="out_power_units">
			<spawn_ex name="western_fortress_out_power_units"/>
		</objects>
		<objects name="in_power_units">
			<spawn_ex name="western_fortress_in_power_units"/>
		</objects>
		<objects name="siege_zones">
			<zone name="[a_o_g_fort_siege]"/>
		</objects>
		<objects name="flag_zones">
			<zone name="[a_o_g_fort_hq]"/>
		</objects>
	</event>
</list>
