=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/events.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (event)*>
<!ELEMENT event (parameter|on_start|on_stop|on_init|on_time|objects)*>
<!ATTLIST event
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT on_start  (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on_stop   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on_init   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT on        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT if        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT ifnot     (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ELEMENT else      (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward|global_remove_items)*>
<!ATTLIST if
	name CDATA #REQUIRED>
<!ATTLIST ifnot
	name CDATA #REQUIRED>
<!ELEMENT on_time (on)*>
<!ATTLIST on
	time CDATA #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ATTLIST start
	name CDATA #REQUIRED>
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop
	name CDATA #REQUIRED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	name CDATA #REQUIRED>
<!ELEMENT open (#PCDATA)>
<!ATTLIST open
	name CDATA #REQUIRED>
<!ELEMENT close (#PCDATA)>
<!ATTLIST close
	name CDATA #REQUIRED>
<!ELEMENT active (#PCDATA)>
<!ATTLIST active
	name CDATA #REQUIRED>
<!ELEMENT deactive (#PCDATA)>
<!ATTLIST deactive
	name CDATA #REQUIRED>
<!ELEMENT refresh (#PCDATA)>
<!ATTLIST refresh
	name CDATA #REQUIRED>
<!ELEMENT init (#PCDATA)>
<!ATTLIST init
	name CDATA #REQUIRED>
<!ELEMENT announce (#PCDATA)>
<!ATTLIST announce
	msg_id CDATA #IMPLIED
	val CDATA #IMPLIED>
<!ELEMENT despawn (#PCDATA)>
<!ATTLIST despawn
	name CDATA #REQUIRED>
<!ELEMENT respawn (#PCDATA)>
<!ATTLIST respawn
	name CDATA #REQUIRED>
<!ELEMENT global_add_reward (#PCDATA)>
<!ATTLIST global_add_reward
	name CDATA #REQUIRED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>
<!ELEMENT global_remove_reward (#PCDATA)>
<!ATTLIST global_remove_reward
	name CDATA #REQUIRED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>
<!ELEMENT global_remove_items (#PCDATA)>
<!ATTLIST global_remove_items
	name CDATA #REQUIRED>
<!ELEMENT objects (door|spawn|spawn_ex|spawn_npc|point|boat_point|static_object|siege_toggle_npc|castle_zone|combat_flag|ctb_team|cmg_arena|territory_ward|zone|reward|rewardlist|abnormal|item)*>
<!ATTLIST objects
	name CDATA #REQUIRED>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ELEMENT siege_toggle_npc (objects)*>
<!ATTLIST siege_toggle_npc
	id CDATA #REQUIRED
	fake_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	hp CDATA #REQUIRED>
<!ELEMENT castle_zone (#PCDATA)>
<!ATTLIST castle_zone
	name CDATA #REQUIRED
	price CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED>
<!ELEMENT static_object (#PCDATA)>
<!ATTLIST static_object
	id CDATA #REQUIRED>
<!ELEMENT spawn_ex (#PCDATA)>
<!ATTLIST spawn_ex
	name CDATA #REQUIRED>
<!ELEMENT spawn_npc (#PCDATA)>
<!ATTLIST spawn_npc
	id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT combat_flag (#PCDATA)>
<!ATTLIST combat_flag
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT territory_ward (#PCDATA)>
<!ATTLIST territory_ward
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT ctb_team (#PCDATA)>
<!ATTLIST ctb_team
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #REQUIRED
	id CDATA #REQUIRED
	mob_id CDATA #REQUIRED>
<!ELEMENT cmg_arena (#PCDATA)>
<!ELEMENT boat_point (#PCDATA)>
<!ATTLIST boat_point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	speed1 CDATA #REQUIRED
	speed2 CDATA #REQUIRED
	fuel CDATA #IMPLIED
	teleport CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT npc_say (add)*>
<!ATTLIST npc_say
	npc CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT add (#PCDATA)*>
<!ATTLIST add
	value CDATA #REQUIRED>
<!ELEMENT teleport_players (#PCDATA)*>
<!ATTLIST teleport_players
	id CDATA #REQUIRED>
<!ELEMENT say (#PCDATA)>
<!ATTLIST say
	how CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT play_sound (#PCDATA)>
<!ATTLIST play_sound
	type CDATA #REQUIRED
	sound CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT give_item (#PCDATA)>
<!ATTLIST give_item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT rewardlist (group|reward)*>
<!ATTLIST rewardlist
	type CDATA #REQUIRED>
<!ELEMENT group (reward)*>
<!ATTLIST group
	chance CDATA #IMPLIED>
<!ELEMENT reward (#PCDATA)>
<!ATTLIST reward
	chance CDATA #REQUIRED
	item_id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED>
<!ELEMENT abnormal (#PCDATA)>
<!ATTLIST abnormal
		name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED
	count CDATA #IMPLIED>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/siege/[106] narsell_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="106" name="Narsell Fortress" impl="FortressSiege">
		<on_init>
			<spawn name="fortress_peace_npcs"/>
			<init name="upgradeable_doors"/>
			<init name="commander_doors"/>
			<init name="enter_doors"/>
			<init name="siege_zones"/>
			<init name="flag_zones"/>
			<spawn name="flag_pole"/>
			<spawn name="peace_commanders"/>
		</on_init>
		<on_start>
			<despawn name="peace_commanders"/>
			<!--Спавним гвардов-->
			<spawn name="default_guards"/>
			<spawn name="guards_live_with_c_center"/>
			<spawn name="siege_commanders"/>
			<if name="old_owner">
				<spawn name="owner_flagdef"/>
				<spawn name="mercenary"/>
			</if>
			<else>
				<spawn name="noowner_flagdef"/>
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1"/>
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2"/>
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens"/>
			</if>
			<!--Обновляем двери-->
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<active name="siege_zones"/>
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="owner_flagdef"/>
				<despawn name="mercenary"/>
			</if>
			<else>
				<despawn name="noowner_flagdef"/>
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards"/>
			<despawn name="guards_live_with_c_center"/>
			<despawn name="siege_commanders"/>

			<!--Капитаны и менчант-->
			<spawn name="peace_commanders"/>

			<!--Обновляем двери-->
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<teleport_players id="spectators"/>
			<deactive name="siege_zones"/>
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600"/>
			</on>
			<on time="-1800">
				<announce val="1800"/>
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600"/>
				<stop name="registration"/>
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5"/>
			</on>
			<on time="-4">
				<announce val="4"/>
			</on>
			<on time="-3">
				<announce val="3"/>
			</on>
			<on time="-2">
				<announce val="2"/>
			</on>
			<on time="-1">
				<announce val="1"/>
			</on>
			<on time="0">
				<start name="event"/>
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="600">
				<give_item id="-300" count="310"/>
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="900">
				<give_item id="-300" count="310"/>
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="1200">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="1500">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="1800">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="2100">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="2400">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="2700">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="3000">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="3300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="3600">
				<stop name="event"/>
			</on>
		</on_time>
		<objects name="fortress_peace_npcs">
			<spawn name="narsell_fortress_106"/>
		</objects>
		<objects name="merchant">
			<spawn_ex name="narsell_fortress_peace_merchant"/>
		</objects>
		<objects name="flag_pole">
			<static_object id="24190500"/>
		</objects>
		<objects name="combat_flags">
			<combat_flag x="154638" y="55407" z="-3123"/>
			<combat_flag x="154687" y="55480" z="-3123"/>
			<combat_flag x="154742" y="55541" z="-3123"/>
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="narsell_fortress_peace_commanders"/>
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="narsell_fortress_siege_commanders"/>
		</objects>
		<objects name="envoy">
			<spawn_ex name="narsell_fortress_envoy"/>
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="narsell_fortress_default_guards"/>
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="narsell_fortress_live_with_c_center"/>
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="narsell_fortress_noowner_flagdef"/>
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="narsell_fortress_owner_flagdef"/>
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="narsell_fortress_gunner"/>
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="narsell_fortress_reinforce_1"/>
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="narsell_fortress_reinforce_2"/>
		</objects>
		<objects name="enter_doors">
			<door id="24190005"/>
			<door id="24190010"/>
		</objects>
		<objects name="upgradeable_doors">
			<door id="24190005"/>
			<door id="24190010"/>
			<door id="24190011"/>
			<door id="24190012"/>
		</objects>
		<objects name="commander_doors">
			<door id="24190006"/>
			<door id="24190007"/>
			<door id="24190008"/>
			<door id="24190009"/>
		</objects>
		<objects name="mercenary_points">
			<point x="151251" y="58391" z="-3368"/>
			<point x="151526" y="58194" z="-3296"/>
			<point x="151782" y="57978" z="-3280"/>
			<point x="152220" y="57619" z="-3280"/>
			<point x="152573" y="57328" z="-3280"/>
			<point x="152890" y="57077" z="-3248"/>
			<point x="153146" y="56857" z="-3256"/>
			<point x="153514" y="56539" z="-3256"/>
			<point x="153870" y="56202" z="-3256"/>
			<point x="154264" y="55835" z="-3256"/>
		</objects>
		<objects name="mercenary">
			<spawn_ex name="narsell_fortress_mercenary"/>
		</objects>
		<objects name="siege_zones">
			<zone name="[aden_fort_a_siege]"/>
		</objects>
		<objects name="flag_zones">
			<zone name="[aden_fort_a_hq]"/>
		</objects>
	</event>
</list>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/shuttle/[2] CityOfArcan2_Shuttle.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<!--AUTHOR: Bonux-->
<list>
	<event id="200" name="CityOfArcan2_Shuttle" impl="ShuttleWay">
		<parameter name="shuttle_id" value="2"/>
		<parameter name="spawn_point" value="209885 83357 -1035 0"/>
		<parameter name="next_floor_loc" value="209885 83357 85"/>
		<parameter name="floor_doors_id" value="0"/>
		<parameter name="speed" value="300"/>
		<parameter name="return_point" value="209428 83662 -992"/>
		<on_init>
			<init name="doors"/>
		</on_init>
		<on_start>
			<close name="doors"/>
		</on_start>
		<on_time>
			<on time="0">
				<open name="doors"/>
			</on>
			<on time="17">
				<start name="event"/>
			</on>
		</on_time>
		<objects name="doors">
			<door id="26200003"/>
		</objects>
	</event>
	<event id="201" name="CityOfArcan2_Shuttle" impl="ShuttleWay">
		<parameter name="next_floor_loc" value="209885 83357 -1035"/>
		<parameter name="floor_doors_id" value="1"/>
		<parameter name="speed" value="300"/>
		<parameter name="return_point" value="209428 83662 -992"/>
		<on_init>
			<init name="doors"/>
		</on_init>
		<on_start>
			<close name="doors"/>
		</on_start>
		<on_time>
			<on time="0">
				<open name="doors"/>
			</on>
			<on time="17">
				<start name="event"/>
			</on>
		</on_time>
		<objects name="doors">
			<door id="26200004"/>
		</objects>
	</event>
</list>

=== mistermausee-cmd/lineage2/l2scripts/dist/gameserver/data/events/siege/[104] valley_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="104" name="Valley Fortress" impl="FortressSiege">
		<on_init>
			<spawn name="fortress_peace_npcs"/>
			<init name="upgradeable_doors"/>
			<init name="commander_doors"/>
			<init name="enter_doors"/>
			<init name="machine_doors"/>
			<init name="siege_zones"/>
			<init name="flag_zones"/>
			<spawn name="flag_pole"/>
			<spawn name="peace_commanders"/>
		</on_init>
		<on_start>
			<despawn name="peace_commanders"/>
			<!--Спавним гвардов-->
			<spawn name="default_guards"/>
			<spawn name="guards_live_with_c_center"/>
			<spawn name="siege_commanders"/>
			<spawn name="out_power_units"/>
			<spawn name="in_power_units"/>
			<if name="old_owner">
				<spawn name="owner_flagdef"/>
				<spawn name="mercenary"/>
			</if>
			<else>
				<spawn name="noowner_flagdef"/>
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1"/>
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2"/>
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens"/>
			</if>
			<!--Обновляем двери-->
			<refresh name="enter_doors"/>
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<refresh name="machine_doors"/>
			<active name="siege_zones"/>
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="owner_flagdef"/>
				<despawn name="mercenary"/>
			</if>
			<else>
				<despawn name="noowner_flagdef"/>
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards"/>
			<despawn name="guards_live_with_c_center"/>
			<despawn name="siege_commanders"/>
			<despawn name="out_power_units"/>
			<despawn name="in_power_units"/>

			<!--Капитаны и менчант-->
			<spawn name="peace_commanders"/>

			<!--Обновляем двери-->
			<refresh name="enter_doors"/>
			<refresh name="upgradeable_doors"/>
			<refresh name="commander_doors"/>
			<refresh name="machine_doors"/>
			<teleport_players id="spectators"/>
			<deactive name="siege_zones"/>
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600"/>
			</on>
			<on time="-1800">
				<announce val="1800"/>
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600"/>
				<stop name="registration"/>
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5"/>
			</on>
			<on time="-4">
				<announce val="4"/>
			</on>
			<on time="-3">
				<announce val="3"/>
			</on>
			<on time="-2">
				<announce val="2"/>
			</on>
			<on time="-1">
				<announce val="1"/>
			</on>
			<on time="0">
				<start name="event"/>
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="600">
				<give_item id="-300" count="310"/>
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="900">
				<give_item id="-300" count="310"/>
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="1200">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="1500">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="1800">
				<give_item id="-300" count="310"/>
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="2100">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="2400">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01"/>
			</on>
			<on time="2700">
				<give_item id="-300" count="310"/>
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F"/>
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01"/>
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F"/>
			</on>
			<on time="3000">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F"/>
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01"/>
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F"/>
			</on>
			<on time="3300">
				<give_item id="-300" count="310"/>
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F"/>
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01"/>
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F"/>
			</on>
			<on time="3600">
				<stop name="event"/>
			</on>
		</on_time>
		<objects name="fortress_peace_npcs">
			<spawn name="valley_fortress_104"/>
		</objects>
		<objects name="merchant">
			<spawn_ex name="valley_fortress_peace_merchant"/>
		</objects>
		<objects name="flag_pole">
			<static_object id="23210500"/>
		</objects>
		<objects name="combat_flags">
			<combat_flag x="125991" y="123616" z="-2454"/>
			<combat_flag x="126072" y="123622" z="-2454"/>
			<combat_flag x="126157" y="123622" z="-2454"/>
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="valley_fortress_peace_commanders"/>
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="valley_fortress_siege_commanders"/>
		</objects>
		<objects name="envoy">
			<spawn_ex name="valley_fortress_envoy"/>
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="valley_fortress_default_guards"/>
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="valley_fortress_live_with_c_center"/>
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="valley_fortress_noowner_flagdef"/>
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="valley_fortress_owner_flagdef"/>
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="valley_fortress_gunner"/>
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="valley_fortress_reinforce_1"/>
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="valley_fortress_reinforce_2"/>
		</objects>
		<objects name="enter_doors">
			<door id="23210001"/>
			<door id="23210012"/>
		</objects>
		<objects name="machine_doors">
			<door id="23210002"/>
			<door id="23210003"/>
		</objects>
		<objects name="upgradeable_doors">
			<door id="23210001"/>
			<door id="23210004"/>
			<door id="23210005"/>
			<door id="23210008"/>
			<door id="23210009"/>
			<door id="23210012"/>
		</objects>
		<objects name="commander_doors">
			<door id="23210006"/>
			<door id="23210007"/>
			<door id="23210010"/>
			<door id="23210011"/>
		</objects>
		<objects name="mercenary_points">
			<point x="125966" y="118875" z="-3016"/>
			<point x="125991" y="119142" z="-2896"/>
			<point x="125976" y="119436" z="-2760"/>
			<point x="126001" y="119761" z="-2664"/>
			<point x="126061" y="120052" z="-2600"/>
			<point x="126061" y="120386" z="-2584"/>
			<point x="126064" y="120721" z="-2584"/>
			<point x="126066" y="121173" z="-2584"/>
			<point x="126065" y="121854" z="-2584"/>
			<point x="126076" y="122539" z="-2584"/>
		</objects>
		<objects name="mercenary">
			<spawn_ex name="valley_fortress_mercenary"/>
		</objects>
		<objects name="out_power_units">
			<spawn_ex name="valley_fortress_out_power_units"/>
		</objects>
		<objects name="in_power_units">
			<spawn_ex name="valley_fortress_in_power_units"/>
		</objects>
		<objects name="siege_zones">
			<zone name="[giran_fort_siege]"/>
		</objects>
		<objects name="flag_zones">
			<zone name="[giran_fort_hq]"/>
		</objects>
	</event>
</list>
